// All Gwalior locations in one place
export const GWALIOR_LOCATIONS = [
  "DD Nagar",
  "City Centre",
  "Lashkar",
  "Thatipur",
  "Morar",
  "Gola Ka Mandir",
  "Maharajpura",
  "Padav",
  "Hazira",
  "Jhansi Road",
  "Kampoo",
  "University Road",
  "Gwalior Fort Area",
  "Birla Nagar",
  "Tansen Nagar",
  "Madhav Ganj",
  "Bahodapur",
  "Dabra Road",
  "Vijay Nagar",
  "Sikandarpura",
  "Phool Bagh",
  "Naya Bazar",
  "Sarafa Bazar",
  "MLB Road",
  "Jayendraganj",
  "Huravali",
  "Murar",
  "Kila Gate",
  "Reti Ghar",
  "Lohamandi",
  "Daulat Ganj",
  "Nai Sadak",
  "Gandhi Road",
  "Inderganj",
];

export const PROPERTY_TYPES = ["Flat", "House", "Villa", "Plot", "Shop", "Office", "PG/Hostel", "Farm House"];

export const POPULAR_LOCATIONS = [
  { name: "DD Nagar", icon: "🏘️", desc: "Premium Residential" },
  { name: "City Centre", icon: "🏙️", desc: "Commercial Hub" },
  { name: "Lashkar", icon: "🏛️", desc: "Heritage Area" },
  { name: "Thatipur", icon: "🌳", desc: "Growing Locality" },
  { name: "Morar", icon: "🏗️", desc: "Developing Area" },
  { name: "Gola Ka Mandir", icon: "🕉️", desc: "Well Connected" },
  { name: "Maharajpura", icon: "✈️", desc: "Near Airport" },
  { name: "Padav", icon: "🚉", desc: "Near Railway" },
];
